name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install Project Dependencies
        run: npm install
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules

  check-formatter:
    name: Check formatter
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Check formatter
        run: npm run format:check

  check-linter:
    name: Check linter
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Check linter
        run: npm run lint

  build:
    name: Check build
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: build project
        run: npm run build
      - name: Cacheing build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{github.sha}}-build

  test:
    name: Test project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Run unit test
        run: npm run test

  automerge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: update version
        run: npm version patch
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
