name: Check code and publish to npm
on:
  push:
    branches: main

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install Project Dependencies
        run: npm install
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules

  check-formatter:
    name: Check formatter
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Check formatter
        run: npm run format:check

  check-linter:
    name: Check linter
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Check linter
        run: npm run lint

  build:
    name: Check build
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: build project
        run: npm run build
      - name: Cacheing build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{github.sha}}-build

  test:
    name: Test project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Run unit test
        run: npm run test

  generate-docker:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Restore dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{github.sha}}-node_modules
      - name: Restore build
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          path: build
          key: ${{github.sha}}-build
      - name: Show folder
        run: ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
